### ISSUE TITLE
Error on Python 2 when using functools.partial as a callback

### ISSUE THREAD

**Issue by SpotlightKid** [dsacre/pyliblo#12]
My code is basically:

```
from functools import partial

import liblo
from midibackend import open_output

def on_osc(sink, path, args, types, src):
    pass

server = liblo.ServerThread(port)
midi_out = open_output()  # in reality, 'mido' is used here
server.add_method('/midi', 'm', partial(on_osc, midi_out))
```

This works in Python 3 but not Python 2, where I get this error on every received message:

```
Exception TypeError: TypeError('<functools.partial object at 0x7f7d7deb9f18> is not a Python function',) in 'liblo._msg_callback' ignored
```

I know I could wrap `on_osc` in a class or use a wrapped function, but `partial` seems more convenient to me so I would be nice, if it was supported.

**Comment by SpotlightKid** [comment]
Just noticed that classes with a `__call__` method do also not work:

```
class OscHandler(object):
    def __call__(self, *args. *kwargs):
       pass

[...]

server.add_method('/midi', 'm', OscHandler())
```

```
Exception TypeError: TypeError('<blah.OscHandler object at 0x7f550bbfc9d0> is not a Python function',) in 'liblo._msg_callback' ignored
```

**Comment by dsacre** [comment]
pyliblo uses `inspect.getargspec()` to determine which (or rather, how many) arguments a callback function accepts. In Python 2 `getargspec()` doesn't work for all callables, so it should be called on the `__call__` member rather than on the object itself. I'll prepare a patch for pyliblo.

**Comment by SpotlightKid** [comment]
Cool. Thanks!

**Comment by dsacre** [comment]
Could you check if 4c8f730519299a58ed6f7cda3bcecc3de3307abe works for you?

**Comment by SpotlightKid** [comment]
Not quite. Here's my test code:

```
from functools import partial

import liblo
PORT = 9000

def handle_osc1(self, foo, path, args, types, src):
    print("Args:", foo, path, args, types, src)

def handle_osc2(self, path, args, types, src, foo="bar"):
    print("Args:", path, args, types, src, foo)

class OSCHandler1(object):
    def __call__(self, *args, **kw):
        print("Self:", self)
        print("Args:", args)
        print("KWargs:", kw)

class OSCHandler2(object):
    def __call__(self, path, args, types, src):
        print("Self:", self)
        print("Args:", path, args, types, src)

server = liblo.ServerThread(PORT)
server.add_method("/test1", None, OSCHandler1())
server.add_method("/test2", None, OSCHandler2())
server.add_method("/test3", None, partial(handle_osc1, 'spamm'))
server.add_method("/test4", None, partial(handle_osc2, foo='spamm'))

try:
    while True:
        server.start()
except KeyboardInterrupt:
    server.stop()
    server.free()
```

I test with:

```
send_osc 9000 /test1 ,f 1.0
send_osc 9000 /test2 ,f 1.0
send_osc 9000 /test3 ,f 1.0
send_osc 9000 /test4 ,f 1.0
```

This gives the following server output (tested Python 3.4 and Python 2.7):

```
Self: <__main__.OSCHandler1 object at 0x7fc73c8b5828>
Args: ('/test1', [1.0], 'f', <liblo.Address object at 0x7fc73c9b7360>, None)
KWargs: {}
Self: <__main__.OSCHandler2 object at 0x7f8d047672e8>
Args: /test2 [1.0] f <liblo.Address object at 0x7f8d06243360>
Args: /test3 [1.0] f <liblo.Address object at 0x7fc73c9b7360> None
Args: [1.0] f <liblo.Address object at 0x7fc9f7cc1360> None spamm
```

* `OSCHander1` and `OSCHandler2` and `handle_osc2` work fine.
* With `handle_osc1` wrapped by a partial pyliblo misinterprets the signature and 'spam' gets somehow dropped.

**Comment by dsacre** [comment]
I believe `handle_osc1` will work as expected if you remove the `self` parameter :)

However, `handle_osc2` shows an actual problem with my current approach, because `partial` objects with keyword arguments are not handled correctly. In Python 2 (and up to 3.3 AFAICT), `getargspec()` accepts neither a `partial` object (because it's not a function) nor its `__call__` method (because it's written in C). I'm not sure what to do about that yet.

**Comment by SpotlightKid** [comment]
Oops! :) However, glad I brought you on to something!

**Comment by dsacre** [comment]
Please give e897f9987dc97fc678d61ac0e16fe79c6a7dffc0 a try.

**Comment by SpotlightKid** [comment]
Looks good (tested with 2.7, 3.4 and 3.5) *but* Python 3.5 issues this warning:

```
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
```

Looks like you need a version-dependent switch there.

**Comment by SpotlightKid** [comment]
BTW, what's the recommended way to run the tests?

**Comment by dsacre** [comment]
Thanks for the heads-up.
I've merged fixes for the issues mentioned here into the master branch.

I tend to use `python3 -m unittest discover` or `unit2 discover` to run the tests. But `./setup.py test` or simply `./test/test_liblo.py` should also work.

**Comment by velolala** [comment]
Excuse the resurrection, but this fix doesn't seem to be released?

**Comment by ideoforms** [comment]
@velolala It looks like the fix isn't in the last-released PyPi version.
You can work around it by installing liblo direct from GitHub:
```
pip install git+ssh://git@github.com/dsacre/pyliblo.git
```
