### ISSUE TITLE
Version 0.10.0 is listed on pypi, but can't be installed via pip

### ISSUE THREAD

**Issue by ch3pjw** [dsacre/pyliblo#14]
I'm trying to install the latest release of `pyliblo` using `pip`, but it appears that although 0.10.0 shows up on the human facing interface (https://pypi.python.org/pypi/pyliblo), there's no corresponding source for it (https://pypi.python.org/simple/pyliblo/).

This means `pip install pyliblo` gives me 0.9.2 even in a clean virtualenv, whereas I would expect to get the latest as advertised on pypi.

**Comment by foolswood** [comment]
Any ideas on this?

**Comment by dsacre** [comment]
I'm not quite sure what happened here, but I re-uploaded the tarball, and pip now installs 0.10.0 by default. Sorry for taking so long...
