### ISSUE TITLE
liblo.c is missing

### ISSUE THREAD

**Issue by arminbw** [dsacre/pyliblo#7]
The README file states that liblo's C Cython source file is included in the pyliblo distribution. This is not the case in the 0.10.0 version. The build process fails.

After I copied the file from pyliblo 0.9.1, setup couldn't find ```lo/lo.h```. So I downloaded liblo, built and installed it. Afterwards I was able to compile pyliblo, but I still needed the liblo.c file I stole from 0.9.1.

**Comment by dsacre** [comment]
Thanks for the heads up. The current version of the README refers only to the release tarballs at http://das.nasophon.de/pyliblo, all of which do include `liblo.c`.

Note that `liblo.c` is generated from `liblo.pyx` by running `./setup.py build --with-cython`. If you just copy liblo.c from an older release, you're effectively building that old version of pyliblo.

For the 0.10.0 release I'd like to drop the pre-generated `liblo.c` from the tarball altogether, making Cython a mandatory build dependency. Shipping the generated C code with the tarball is mostly a remnant from early versions of pyliblo, at a time when most Linux distributions lacked sufficiently recent versions of Pyrex/Cython.

**Comment by Jacalz** [comment]
Sorry to dig up an old issue, but I am running in to the exact same issue. Seems like liblo header file on Solus (my linux distro) is at /usr/include/ and library at /usr/lib64. How would I tell the compiler to find them?
